#!/usr/bin/env python3
"""
Setup script for Football Analytics Platform
This script helps you configure your API key and environment variables
"""

import os
import sys

def create_env_file():
    """Create a .env file with the user's API key"""
    
    print("⚽ Football Analytics Platform Setup")
    print("=" * 50)
    
    # Check if .env already exists
    if os.path.exists('.env'):
        print("⚠️  .env file already exists!")
        overwrite = input("Do you want to overwrite it? (y/N): ").lower()
        if overwrite != 'y':
            print("Setup cancelled. Using existing .env file.")
            return
    
    print("\n📋 To use this platform, you need a Football-Data.org API key.")
    print("   Get your free API key from: https://www.football-data.org/client/register")
    print()
    
    # Get API key from user
    api_key = input("Enter your Football-Data.org API key: ").strip()
    
    if not api_key:
        print("❌ API key is required. Setup cancelled.")
        return
    
    # Create .env file
    env_content = f"""# Football-Data.org API Configuration
# Generated by setup.py
FOOTBALL_DATA_API_KEY={api_key}

# Other configuration options
# API_BASE_URL=https://api.football-data.org/v4
# DEBUG_MODE=true
"""
    
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        
        print("✅ .env file created successfully!")
        print("🔑 Your API key has been saved.")
        print("\n🚀 You can now run the API with: python api.py")
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")
        print("Please create the file manually with your API key.")

def check_requirements():
    """Check if required packages are installed"""
    print("\n📦 Checking required packages...")
    
    required_packages = [
        'fastapi',
        'uvicorn',
        'requests',
        'python-dotenv'
    ]
    
    missing_packages = []
    
    for package in required_packages:
        try:
            __import__(package.replace('-', '_'))
            print(f"✅ {package}")
        except ImportError:
            print(f"❌ {package} - MISSING")
            missing_packages.append(package)
    
    if missing_packages:
        print(f"\n⚠️  Missing packages: {', '.join(missing_packages)}")
        print("Install them with: pip install -r requirements.txt")
        return False
    
    print("✅ All required packages are installed!")
    return True

def main():
    """Main setup function"""
    print("Setting up Football Analytics Platform...")
    
    # Check requirements first
    if not check_requirements():
        print("\n❌ Please install missing packages before continuing.")
        sys.exit(1)
    
    # Create .env file
    create_env_file()
    
    print("\n🎉 Setup complete!")
    print("\nNext steps:")
    print("1. Make sure your .env file contains your API key")
    print("2. Run the API: python api.py")
    print("3. In another terminal, start the frontend: cd ../frontend && npm start")

if __name__ == "__main__":
    main()
